spring:
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://localhost:5432/goods
    username: admin
    password: admin
mybatis:
  mapper-locations: classpath:mapper/**/**.xml
  configuration:
    map-underscore-to-camel-case: true
